spring.application.name=api-gateway
server.port=8765

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
spring.config.import=optional:configserver:http://localhost:8888

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lowerCaseServiceId=true

spring.cloud.gateway.routes[0].id=wallet-service
spring.cloud.gateway.routes[0].uri=lb://WALLET-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/wallet/**

spring.cloud.gateway.routes[1].id=inventory-service
spring.cloud.gateway.routes[1].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/createProduct/**

spring.cloud.gateway.routes[2].id=shop-service
spring.cloud.gateway.routes[2].uri=lb://SHOP-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/addProductToCart/**